package:
  format-version: "1.0.0"
  name: "csp"
  version: "v3.18.1"
  type: "api"
  status: "production"
  required: true

  dependencies:
    - name: "dev_packs"
      type: "package"
      version: "v3.18.0"
    - name: "CMSIS_5"
      type: "package"
      version: "5.8.0"
    - name: "harmony-services"
      type: "package"
      version: "v1.2.1"
    - name: "CEC_DFP"
      type: "dfp"
      version: "1.8.258"
    - name: "LAN9255_DFP"
      type: "dfp"
      version: "1.3.20"
    - name: "PIC32CK-GC_DFP"
      type: "dfp"
      version: "1.0.131"
    - name: "PIC32CK-SG_DFP"
      type: "dfp"
      version: "1.0.141"
    - name: "PIC32CM-JH_DFP"
      type: "dfp"
      version: "1.1.203"
    - name: "PIC32CM-LE_DFP"
      type: "dfp"
      version: "1.2.273"
    - name: "PIC32CM-LS_DFP"
      type: "dfp"
      version: "1.2.274"
    - name: "PIC32CM-MC_DFP"
      type: "dfp"
      version: "1.4.67"
    - name: "PIC32CX-BZ_DFP"
      type: "dfp"
      version: "1.3.238"
    - name: "PIC32CX-BZ3_DFP"
      type: "dfp"
      version: "1.1.171"
    - name: "PIC32CX-MT_DFP"
      type: "dfp"
      version: "1.1.115"
    - name: "PIC32CX-SG41_DFP"
      type: "dfp"
      version: "1.1.122"
    - name: "PIC32CX-SG60_DFP"
      type: "dfp"
      version: "1.1.122"
    - name: "PIC32CX-SG61_DFP"
      type: "dfp"
      version: "1.1.122"
    - name: "PIC32CZ-CA80_DFP"
      type: "dfp"
      version: "1.2.150"
    - name: "PIC32CZ-CA90_DFP"
      type: "dfp"
      version: "1.3.152"
    - name: "PIC32CZ-CA91_DFP"
      type: "dfp"
      version: "1.0.11"
    - name: "PIC32MK-GP_DFP"
      type: "dfp"
      version: "1.6.144"
    - name: "PIC32MK-MC_DFP"
      type: "dfp"
      version: "1.11.151"
    - name: "PIC32MM-GPL-0XX_DFP"
      type: "dfp"
      version: "1.3.57"
    - name: "PIC32MM-GPM-0XX_DFP"
      type: "dfp"
      version: "1.3.50"
    - name: "PIC32MX_DFP"
      type: "dfp"
      version: "1.5.259"
    - name: "PIC32MZ-DA_DFP"
      type: "dfp"
      version: "1.4.118"
    - name: "PIC32MZ-EF_DFP"
      type: "dfp"
      version: "1.3.58"
    - name: "PIC32MZ-W_DFP"
      type: "dfp"
      version: "1.8.326"
    - name: "SAM9X6_DFP"
      type: "dfp"
      version: "1.7.85"
    - name: "SAM9X7_DFP"
      type: "dfp"
      version: "1.1.120"
    - name: "SAMA5D2_DFP"
      type: "dfp"
      version: "1.9.106"
    - name: "SAMA7G5_DFP"
      type: "dfp"
      version: "1.2.178"
    - name: "SAMC20_DFP"
      type: "dfp"
      version: "3.5.93"
    - name: "SAMC21_DFP"
      type: "dfp"
      version: "3.8.119"
    - name: "SAMD09_DFP"
      type: "dfp"
      version: "2.5.147"
    - name: "SAMD10_DFP"
      type: "dfp"
      version: "2.7.81"
    - name: "SAMD11_DFP"
      type: "dfp"
      version: "2.6.76"
    - name: "SAMD20_DFP"
      type: "dfp"
      version: "3.6.112"
    - name: "SAMD21_DFP"
      type: "dfp"
      version: "3.6.144"
    - name: "SAMD51_DFP"
      type: "dfp"
      version: "3.7.237"
    - name: "SAMDA1_DFP"
      type: "dfp"
      version: "2.7.82"
    - name: "SAME51_DFP"
      type: "dfp"
      version: "3.7.242"
    - name: "SAME53_DFP"
      type: "dfp"
      version: "3.7.228"
    - name: "SAME54_DFP"
      type: "dfp"
      version: "3.8.234"
    - name: "SAME70_DFP"
      type: "dfp"
      version: "4.10.248"
    - name: "SAMG_DFP"
      type: "dfp"
      version: "3.8.197"
    - name: "SAMHA0_DFP"
      type: "dfp"
      version: "2.2.63"
    - name: "SAMHA1_DFP"
      type: "dfp"
      version: "2.4.81"
    - name: "SAML10_DFP"
      type: "dfp"
      version: "3.10.228"
    - name: "SAML11_DFP"
      type: "dfp"
      version: "4.5.268"
    - name: "SAML21_DFP"
      type: "dfp"
      version: "3.7.217"
    - name: "SAML22_DFP"
      type: "dfp"
      version: "3.7.83"
    - name: "SAMR21_DFP"
      type: "dfp"
      version: "2.0.52"
    - name: "SAMR30_DFP"
      type: "dfp"
      version: "2.0.47"
    - name: "SAMR34_DFP"
      type: "dfp"
      version: "2.1.61"
    - name: "SAMR35_DFP"
      type: "dfp"
      version: "2.1.63"
    - name: "SAMRH707_DFP"
      type: "dfp"
      version: "1.2.156"
    - name: "SAMRH71_DFP"
      type: "dfp"
      version: "2.5.142"
    - name: "SAMS70_DFP"
      type: "dfp"
      version: "4.10.214"
    - name: "SAMV70_DFP"
      type: "dfp"
      version: "4.10.212"
    - name: "SAMV71_DFP"
      type: "dfp"
      version: "4.10.230"
    - name: "WLR089_DFP"
      type: "dfp"
      version: "1.1.26"
