package:
  format-version: "1.0.0"
  name: "csp"
  version: "v3.22.5"
  type: "api"
  status: "production"
  required: true

  dependencies:
    - name: "CMSIS_5"
      type: "package"
      version: "5.9.0"
    - name: "harmony-services"
      type: "package"
      version: "v1.5.0"
    - name: "CEC_DFP"
      type: "dfp"
      version: "2.0.261"
    - name: "LAN9255_DFP"
      type: "dfp"
      version: "1.3.20"
    - name: "PIC32CK-GC_DFP"
      type: "dfp"
      version: "1.1.148"
    - name: "PIC32CK-SG_DFP"
      type: "dfp"
      version: "1.3.168"
    - name: "PIC32CM-GV_DFP"
      type: "dfp"
      version: "1.0.7"
    - name: "PIC32CM-JH_DFP"
      type: "dfp"
      version: "1.4.224"
    - name: "PIC32CM-LE_DFP"
      type: "dfp"
      version: "1.3.280"
    - name: "PIC32CM-LS_DFP"
      type: "dfp"
      version: "1.3.278"
    - name: "PIC32CM-MC_DFP"
      type: "dfp"
      version: "1.4.67"
    - name: "PIC32CX-BZ_DFP"
      type: "dfp"
      version: "1.4.243"
    - name: "PIC32CX-BZ3_DFP"
      type: "dfp"
      version: "1.3.216"
    - name: "PIC32CX-MT_DFP"
      type: "dfp"
      version: "1.3.132"
    - name: "PIC32CX-SG41_DFP"
      type: "dfp"
      version: "1.5.140"
    - name: "PIC32CX-SG60_DFP"
      type: "dfp"
      version: "1.2.129"
    - name: "PIC32CX-SG61_DFP"
      type: "dfp"
      version: "1.2.124"
    - name: "PIC32CZ-CA70_DFP"
      type: "dfp"
      version: "1.2.32"
    - name: "PIC32CZ-CA80_DFP"
      type: "dfp"
      version: "1.4.158"
    - name: "PIC32CZ-CA90_DFP"
      type: "dfp"
      version: "1.5.162"
    - name: "PIC32CZ-CA91_DFP"
      type: "dfp"
      version: "1.2.18"
    - name: "PIC32CZ-MC70_DFP"
      type: "dfp"
      version: "1.1.26"
    - name: "PIC32MK-GP_DFP"
      type: "dfp"
      version: "1.7.251"
    - name: "PIC32MK-MC_DFP"
      type: "dfp"
      version: "1.11.151"
    - name: "PIC32MM-GPL-0XX_DFP"
      type: "dfp"
      version: "1.4.168"
    - name: "PIC32MM-GPM-0XX_DFP"
      type: "dfp"
      version: "1.4.156"
    - name: "PIC32MX_DFP"
      type: "dfp"
      version: "1.6.369"
    - name: "PIC32MZ-DA_DFP"
      type: "dfp"
      version: "1.5.231"
    - name: "PIC32MZ-EF_DFP"
      type: "dfp"
      version: "1.4.168"
    - name: "PIC32MZ-W_DFP"
      type: "dfp"
      version: "1.9.330"
    - name: "SAM9X6_DFP"
      type: "dfp"
      version: "1.9.218"
    - name: "SAM9X7_DFP"
      type: "dfp"
      version: "1.9.170"
    - name: "SAMA5D2_DFP"
      type: "dfp"
      version: "1.11.228"
    - name: "SAMA7G5_DFP"
      type: "dfp"
      version: "1.8.235"
    - name: "SAMA7D65_DFP"
      type: "dfp"
      version: "1.7.82"
    - name: "SAMC20_DFP"
      type: "dfp"
      version: "3.5.93"
    - name: "SAMC21_DFP"
      type: "dfp"
      version: "3.8.119"
    - name: "SAMD09_DFP"
      type: "dfp"
      version: "2.5.147"
    - name: "SAMD10_DFP"
      type: "dfp"
      version: "2.7.81"
    - name: "SAMD11_DFP"
      type: "dfp"
      version: "2.6.76"
    - name: "SAMD20_DFP"
      type: "dfp"
      version: "3.6.112"
    - name: "SAMD21_DFP"
      type: "dfp"
      version: "3.6.144"
    - name: "SAMD51_DFP"
      type: "dfp"
      version: "3.8.246"
    - name: "SAMDA1_DFP"
      type: "dfp"
      version: "2.7.82"
    - name: "SAME51_DFP"
      type: "dfp"
      version: "3.8.253"
    - name: "SAME53_DFP"
      type: "dfp"
      version: "3.8.235"
    - name: "SAME54_DFP"
      type: "dfp"
      version: "3.9.244"
    - name: "SAME70_DFP"
      type: "dfp"
      version: "4.11.257"
    - name: "SAMG_DFP"
      type: "dfp"
      version: "3.9.204"
    - name: "SAMHA0_DFP"
      type: "dfp"
      version: "2.2.63"
    - name: "SAMHA1_DFP"
      type: "dfp"
      version: "2.4.81"
    - name: "SAML10_DFP"
      type: "dfp"
      version: "3.10.228"
    - name: "SAML11_DFP"
      type: "dfp"
      version: "4.5.268"
    - name: "SAML21_DFP"
      type: "dfp"
      version: "3.7.217"
    - name: "SAML22_DFP"
      type: "dfp"
      version: "3.7.83"
    - name: "SAMR21_DFP"
      type: "dfp"
      version: "2.0.46"
    - name: "SAMR30_DFP"
      type: "dfp"
      version: "2.0.47"
    - name: "SAMR34_DFP"
      type: "dfp"
      version: "2.1.61"
    - name: "SAMR35_DFP"
      type: "dfp"
      version: "2.1.63"
    - name: "SAMRH707_DFP"
      type: "dfp"
      version: "1.2.156"
    - name: "SAMRH71_DFP"
      type: "dfp"
      version: "2.6.253"
    - name: "SAMS70_DFP"
      type: "dfp"
      version: "4.10.214"
    - name: "SAMV70_DFP"
      type: "dfp"
      version: "4.10.212"
    - name: "SAMV71_DFP"
      type: "dfp"
      version: "4.10.230"
    - name: "WLR089_DFP"
      type: "dfp"
      version: "1.1.26"
    - name: "SAMV71-RT_DFP"
      type: "dfp"
      version: "1.0.120"
    - name: "PIC32CM-GC00_DFP"
      type: "dfp"
      version: "1.0.27"
    - name: "PIC32CM-SG00_DFP"
      type: "dfp"
      version: "1.0.31"
    - name: "PIC32CX-BZ6_DFP"
      type: "dfp"
      version: "1.2.17"
    - name: "PIC32AK-GC_DFP"
      type: "dfp"
      version: "1.0.5"
