print("USART module exists: " + str(Peripheral.moduleExists("USART")))
print("USART module ID: " +  str(Peripheral.getModuleID("USART")))
print("USART module version: " +  str(Peripheral.getModuleVersion("USART")))
print("USART module instance count: " +  str(Peripheral.getModuleInstanceCount("USART")))
print('USART module instance names: [%s]' % ', '.join(map(str, Peripheral.getModuleInstanceNames("USART"))))
print("USART module instance exists: " +  str(Peripheral.instanceExists("USART", "USART0")))

print("Interrupt exists: " + str(Interrupt.interruptExists("RTC")))
print("Interrupt exists: " + str(Interrupt.interruptExists(-2)))
print("Min interrupt index: " + str(Interrupt.getMinInterruptID()))
print("Max interrupt index: " + str(Interrupt.getMaxInterruptID()))
print("Interrupt index for RTC: " + str(Interrupt.getInterruptIndex("RTC")))
print("Interrupt name for index 2: " + str(Interrupt.getInterruptName(2)))
print("Interrupt instance name for index 2: " + str(Interrupt.getInterruptInstanceName(2)))
print("Interrupt description for index 2: " + str(Interrupt.getInterruptDescription(2)))

print("Package count: " + str(Pin.getPackageCount()))
names = Pin.getPackageNames()
print('Package names: [%s]' % ', '.join(map(str, names)))
print("Pin count for package " + names[0] + ": " + str(Pin.getPackagePinCount(names[0])))
print("Maximum pin count: " + str(Pin.getMaxPinCount()))
print("Largest package: " + Pin.getLargestPackageName())
pinNames = Pin.getPinPositions(names[0])
print('Pin positions for package ' + names[0] + ': [%s]' % ', '.join(map(str, pinNames)))
print("Pin pad via position: " + Pin.getPinPad(names[0], pinNames[0]))

devCfgMenu = coreComponent.createMenuSymbol(None, None)
devCfgMenu.setLabel("Device Configuration Bits")
devCfgMenu.setDescription("Hardware Configuration Bits")
