print("Loading PIC32CZ2038CA70144 Pin Manager")

portsMenu = coreComponent.createMenuSymbol(None, None)
portsMenu.setLabel("Ports")
portsMenu.setDescription("Configuraiton for Ports System Service")

portsEnable = coreComponent.createBooleanSymbol("portsEnable", portsMenu)
portsEnable.setLabel("Use Ports System Service?")
portsEnable.setDefaultValue(True)
portsEnable.setReadOnly(True)

print("==============================================")
print("Pin Information")
print("")

print("Package count: " + str(Pin.getPackageCount()))
portsPackageNames = Pin.getPackageNames()
print('Package names: [%s]' % ', '.join(map(str, portsPackageNames)))
print("Pin count for package " + portsPackageNames[0] + ": " + str(Pin.getPackagePinCount(portsPackageNames[0])))
print("Largest package: " + Pin.getLargestPackageName())
portsPinNames = Pin.getPinPositions(portsPackageNames[0])
print('Pin positions for package ' + portsPackageNames[0] + ': [%s]' % ', '.join(map(str, portsPinNames)))
print(" Pin " + portsPinNames[0] + " is " + Pin.getPinPad(portsPackageNames[0], portsPinNames[0]))
print(" Pin " + portsPinNames[1] + " is " + Pin.getPinPad(portsPackageNames[0], portsPinNames[1]))
print(" Pin " + portsPinNames[2] + " is " + Pin.getPinPad(portsPackageNames[0], portsPinNames[2]))
print(" Pin " + portsPinNames[3] + " is " + Pin.getPinPad(portsPackageNames[0], portsPinNames[3]))
print("==============================================")
