<#assign NVMCTRL_REG_NAME = NVMCTRL_INSTANCE_NAME>
<#if __TRUSTZONE_ENABLED?? && __TRUSTZONE_ENABLED == "true">
    <#assign NVMCTRL_REG_NAME = NVMCTRL_INSTANCE_NAME + "_SEC">
</#if>
    ${NVMCTRL_REG_NAME}_REGS->NVMCTRL_CTRLB = NVMCTRL_CTRLB_RWS(2);
 